version: "3"
services:
  client:
    image: "sweetyoru/docker-multi-client:latest"
    mem_limit: 256m
    hostname: client

  server:
    image: "sweetyoru/docker-multi-server:latest"
    mem_limit: 256m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres

  worker:
    image: "sweetyoru/docker-multi-worker:latest"
    mem_limit: 256m
    hostname: worker
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379

  nginx:
    image: "sweetyoru/docker-multi-nginx:latest"
    mem_limit: 256m
    hostname: nginx
    ports:
      - "80:80"
